import { getPostBySlug } from "@/lib/api";
import PostBody from "@/components/post-body";
import PostHead from "@/components/post-head";
import markdownStyles from "./markdown-styles.module.css";
import Comment from "@/components/client/comment";

export const metadata = {
  title: "Dayong Blog",
  description: "Generated by create next app",
};

export default async function Post({
  params,
}: {
  params: { slug: string; category: string };
}) {
  const post = getPostBySlug(`${params.category}/${params.slug}`, [
    "title",
    "date",
    "content",
  ]);
  metadata.title = post.title;

  return (
    <div className="flex flex-wrap  justify-center">
      <div className="w-full max-w-screen-md">
        <PostHead title={post.title} date={post.date} category={params.category} />
        <div className={`${markdownStyles["markdown"]} mb-10 border-b border-slate-200 pb-10`}>
          <PostBody content={post.content} />
        </div>
        <Comment />
      </div>
    </div>
  );
}
