import { getAllPosts, getPostBySlug } from '@/lib/api'
import PostBody from '@/components/post-body'
import PostHead from '@/components/post-head'
import markdownStyles from './markdown-styles.module.css'
import Comment from '@/components/client/comment'

export const metadata = {
  title: 'Dayong Blog',
  description: 'Generated by create next app',
}

export default async function Post({
  params,
}: {
  params: { slug: string; category: string }
}) {
  const post = getPostBySlug(`${params.category}/${params.slug}`, [
    'title',
    'date',
    'content',
    'cover',
    'excerpt',
  ])
  metadata.title = post.title
  metadata.description = post.excerpt
  console.log(params)
  return (
    <div className="flex w-full flex-col items-center">
      <PostHead
        title={post.title}
        date={post.date}
        category={params.category}
        cover={post.cover}
      />
      <main
        className={`${markdownStyles['markdown']} mb-10 w-full max-w-screen-md border-b border-slate-200 pb-10`}
      >
        <PostBody content={post.content} category={params.category} />
      </main>
      <div className="w-full max-w-screen-md">
        <Comment />
      </div>
    </div>
  )
}

export async function generateStaticParams() {
  const paths = getAllPosts(['slug', 'category']).map(({ slug, category }) => ({
    slug: slug.replace(category + '/', ''),
    category: category
  }))
  console.log(paths)
  return paths
}
