import "./globals.css";
import Header from "@/components/header";
import { Noto_Sans } from "next/font/google";

const Noto = Noto_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Dayong Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className="light">
      <body className={Noto.className}>
        <Header title={metadata.title} />
        <main className="flex justify-center">
          <div className="w-full max-w-screen-xl p-5">{children}</div>
        </main>
        <footer className="flex h-32 items-center justify-center text-slate-700">
          Copyright © Dayong Lee 2023
        </footer>
      </body>
    </html>
  );
}
