import "./globals.css";
import Header from "@/components/header";

export const metadata = {
  title: "Dayong Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="font-sans">
        <Header title={metadata.title} />
        <main className="w-full flex justify-center">
          <div className="max-w-screen-xl p-5">{children}</div>
        </main>
      </body>
    </html>
  );
}
