import { getPostBySlug } from "@/lib/api";
import markdownToHtml from "@/lib/markdownToHtml";
import PostBody from "@/components/post-body";
import PostHead from "@/components/post-head";
import markdownStyles from "./markdown-styles.module.css";

export const metadata = {
  title: "Dayong Blog",
  description: "Generated by create next app",
};

export default async function Post({
  params,
}: {
  params: { slug: string; category: string };
}) {
  const post = getPostBySlug(`${params.category}/${params.slug}`, [
    "title",
    "author",
    "content",
  ]);
  metadata.title = post.title;
  const content = await markdownToHtml(post.content || "");

  return (
    <div className={markdownStyles["markdown"]}>
      <PostHead title={post.title} author={post.author} />
      <PostBody content={content} />
    </div>
  );
}
